/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as FeatureRouteRouteImport } from './routes/feature/route'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TauriRequiredRouteImport } from './routes/tauri-required'
import { Route as FeatureIndexRouteImport } from './routes/feature/index'
import { Route as FeatureAnimeRouteImport } from './routes/feature/anime'
import { Route as FeatureBilibiliCommentsRouteImport } from './routes/feature/bilibili-comments'
import { Route as FeatureBobingRouteImport } from './routes/feature/bobing'
import { Route as FeatureLotteryRouteImport } from './routes/feature/lottery'
import { Route as FeaturePredictionRouteImport } from './routes/feature/prediction'
import { Route as FeatureRatingRouteImport } from './routes/feature/rating'
import { Route as FeatureTierListRouteImport } from './routes/feature/tier-list'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureRouteRoute = FeatureRouteRouteImport.update({
  id: '/feature',
  path: '/feature',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TauriRequiredRoute = TauriRequiredRouteImport.update({
  id: '/tauri-required',
  path: '/tauri-required',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureIndexRoute = FeatureIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeatureRouteRoute,
} as any)
const FeatureAnimeRoute = FeatureAnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => FeatureRouteRoute,
} as any)
const FeatureBilibiliCommentsRoute = FeatureBilibiliCommentsRouteImport.update({
  id: '/bilibili-comments',
  path: '/bilibili-comments',
  getParentRoute: () => FeatureRouteRoute,
} as any)
const FeatureBobingRoute = FeatureBobingRouteImport.update({
  id: '/bobing',
  path: '/bobing',
  getParentRoute: () => FeatureRouteRoute,
} as any)
const FeatureLotteryRoute = FeatureLotteryRouteImport.update({
  id: '/lottery',
  path: '/lottery',
  getParentRoute: () => FeatureRouteRoute,
} as any)
const FeaturePredictionRoute = FeaturePredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => FeatureRouteRoute,
} as any)
const FeatureRatingRoute = FeatureRatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => FeatureRouteRoute,
} as any)
const FeatureTierListRoute = FeatureTierListRouteImport.update({
  id: '/tier-list',
  path: '/tier-list',
  getParentRoute: () => FeatureRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feature': typeof FeatureRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/tauri-required': typeof TauriRequiredRoute
  '/feature/anime': typeof FeatureAnimeRoute
  '/feature/bilibili-comments': typeof FeatureBilibiliCommentsRoute
  '/feature/bobing': typeof FeatureBobingRoute
  '/feature/lottery': typeof FeatureLotteryRoute
  '/feature/prediction': typeof FeaturePredictionRoute
  '/feature/rating': typeof FeatureRatingRoute
  '/feature/tier-list': typeof FeatureTierListRoute
  '/feature/': typeof FeatureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/tauri-required': typeof TauriRequiredRoute
  '/feature/anime': typeof FeatureAnimeRoute
  '/feature/bilibili-comments': typeof FeatureBilibiliCommentsRoute
  '/feature/bobing': typeof FeatureBobingRoute
  '/feature/lottery': typeof FeatureLotteryRoute
  '/feature/prediction': typeof FeaturePredictionRoute
  '/feature/rating': typeof FeatureRatingRoute
  '/feature/tier-list': typeof FeatureTierListRoute
  '/feature': typeof FeatureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feature': typeof FeatureRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/tauri-required': typeof TauriRequiredRoute
  '/feature/anime': typeof FeatureAnimeRoute
  '/feature/bilibili-comments': typeof FeatureBilibiliCommentsRoute
  '/feature/bobing': typeof FeatureBobingRoute
  '/feature/lottery': typeof FeatureLotteryRoute
  '/feature/prediction': typeof FeaturePredictionRoute
  '/feature/rating': typeof FeatureRatingRoute
  '/feature/tier-list': typeof FeatureTierListRoute
  '/feature/': typeof FeatureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feature'
    | '/about'
    | '/account'
    | '/home'
    | '/library'
    | '/settings'
    | '/tauri-required'
    | '/feature/anime'
    | '/feature/bilibili-comments'
    | '/feature/bobing'
    | '/feature/lottery'
    | '/feature/prediction'
    | '/feature/rating'
    | '/feature/tier-list'
    | '/feature/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/home'
    | '/library'
    | '/settings'
    | '/tauri-required'
    | '/feature/anime'
    | '/feature/bilibili-comments'
    | '/feature/bobing'
    | '/feature/lottery'
    | '/feature/prediction'
    | '/feature/rating'
    | '/feature/tier-list'
    | '/feature'
  id:
    | '__root__'
    | '/'
    | '/feature'
    | '/about'
    | '/account'
    | '/home'
    | '/library'
    | '/settings'
    | '/tauri-required'
    | '/feature/anime'
    | '/feature/bilibili-comments'
    | '/feature/bobing'
    | '/feature/lottery'
    | '/feature/prediction'
    | '/feature/rating'
    | '/feature/tier-list'
    | '/feature/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeatureRouteRoute: typeof FeatureRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  HomeRoute: typeof HomeRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  TauriRequiredRoute: typeof TauriRequiredRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature': {
      id: '/feature'
      path: '/feature'
      fullPath: '/feature'
      preLoaderRoute: typeof FeatureRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tauri-required': {
      id: '/tauri-required'
      path: '/tauri-required'
      fullPath: '/tauri-required'
      preLoaderRoute: typeof TauriRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feature/': {
      id: '/feature/'
      path: '/'
      fullPath: '/feature/'
      preLoaderRoute: typeof FeatureIndexRouteImport
      parentRoute: typeof FeatureRouteRoute
    }
    '/feature/anime': {
      id: '/feature/anime'
      path: '/anime'
      fullPath: '/feature/anime'
      preLoaderRoute: typeof FeatureAnimeRouteImport
      parentRoute: typeof FeatureRouteRoute
    }
    '/feature/bilibili-comments': {
      id: '/feature/bilibili-comments'
      path: '/bilibili-comments'
      fullPath: '/feature/bilibili-comments'
      preLoaderRoute: typeof FeatureBilibiliCommentsRouteImport
      parentRoute: typeof FeatureRouteRoute
    }
    '/feature/bobing': {
      id: '/feature/bobing'
      path: '/bobing'
      fullPath: '/feature/bobing'
      preLoaderRoute: typeof FeatureBobingRouteImport
      parentRoute: typeof FeatureRouteRoute
    }
    '/feature/lottery': {
      id: '/feature/lottery'
      path: '/lottery'
      fullPath: '/feature/lottery'
      preLoaderRoute: typeof FeatureLotteryRouteImport
      parentRoute: typeof FeatureRouteRoute
    }
    '/feature/prediction': {
      id: '/feature/prediction'
      path: '/prediction'
      fullPath: '/feature/prediction'
      preLoaderRoute: typeof FeaturePredictionRouteImport
      parentRoute: typeof FeatureRouteRoute
    }
    '/feature/rating': {
      id: '/feature/rating'
      path: '/rating'
      fullPath: '/feature/rating'
      preLoaderRoute: typeof FeatureRatingRouteImport
      parentRoute: typeof FeatureRouteRoute
    }
    '/feature/tier-list': {
      id: '/feature/tier-list'
      path: '/tier-list'
      fullPath: '/feature/tier-list'
      preLoaderRoute: typeof FeatureTierListRouteImport
      parentRoute: typeof FeatureRouteRoute
    }
  }
}

interface FeatureRouteRouteChildren {
  FeatureAnimeRoute: typeof FeatureAnimeRoute
  FeatureBilibiliCommentsRoute: typeof FeatureBilibiliCommentsRoute
  FeatureBobingRoute: typeof FeatureBobingRoute
  FeatureLotteryRoute: typeof FeatureLotteryRoute
  FeaturePredictionRoute: typeof FeaturePredictionRoute
  FeatureRatingRoute: typeof FeatureRatingRoute
  FeatureTierListRoute: typeof FeatureTierListRoute
  FeatureIndexRoute: typeof FeatureIndexRoute
}

const FeatureRouteRouteChildren: FeatureRouteRouteChildren = {
  FeatureAnimeRoute: FeatureAnimeRoute,
  FeatureBilibiliCommentsRoute: FeatureBilibiliCommentsRoute,
  FeatureBobingRoute: FeatureBobingRoute,
  FeatureLotteryRoute: FeatureLotteryRoute,
  FeaturePredictionRoute: FeaturePredictionRoute,
  FeatureRatingRoute: FeatureRatingRoute,
  FeatureTierListRoute: FeatureTierListRoute,
  FeatureIndexRoute: FeatureIndexRoute,
}

const FeatureRouteRouteWithChildren = FeatureRouteRoute._addFileChildren(
  FeatureRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeatureRouteRoute: FeatureRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  HomeRoute: HomeRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  TauriRequiredRoute: TauriRequiredRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
